config/routes.rb
Rails.application.routes.draw do

  if TemplusModels.configuration.registrar_rotas
    scope "(:locale)" do
      # Routes for RaroCrud
      get '/crud/:model' => "crud#index", as: :crud_models
      get '/crud/:model/:id/edit' => "crud#edit", as: :edit_crud
      delete '/crud/:model/:id/destroy' => "crud#destroy", as: :destroy_crud
      get '/crud/:model/new' => "crud#new", as: :new_crud
      get '/crud/:model/query' => "crud#query", as: :query_crud
      get '/crud/:model/autocomplete' => "crud#autocomplete", as: :autocomplete_crud
      post '/crud/:model/create' => "crud#create", as: :create_crud
      get '/crud/:model/listing' => "crud#listing", as: :listing_crud
      get '/crud/:model/:id/printing' => "crud#printing", as: :printing_crud
      patch '/crud/:model/:id/create' => "crud#create", as: :update_crud
      get '/crud/:model/:id/acao/:acao' => "crud#action", as: :action_crud
      get '/crud/:model/:id' => "crud#show", as: :crud_model

      #Routes for RaroCrud Associations
      get '/crud/:model/:id/:associacao' => "crud#index", as: :crud_associacao_models
      get '/crud/:model/:id/:associacao/:associacao_id/edit' => "crud#edit", as: :edit_crud_associacao
      delete '/crud/:model/:id/:associacao/:associacao_id/destroy' => "crud#destroy", as: :destroy_crud_associacao
      get '/crud/:model/:id/:associacao/new' => "crud#new", as: :new_crud_associacao
      get '/crud/:model/:id/:associacao/query' => "crud#query", as: :query_crud_associacao
      get '/crud/:model/:id/:associacao/autocomplete' => "crud#autocomplete", as: :autocomplete_crud_associacao
      post '/crud/:model/:id/:associacao/create' => "crud#create", as: :create_crud_associacao
      get '/crud/:model/:id/:associacao/listing' => "crud#listing", as: :listing_crud_associacao
      get '/crud/:model/:id/:associacao/printing' => "crud#printing", as: :printing_crud_associacao
      patch '/crud/:model/:id/:associacao/:associacao_id/create' => "crud#create", as: :update_crud_associacao
      get '/crud/:model/:id/:associacao/:associacao_id/acao/:acao' => "crud#action", as: :action_crud_associacao
      get '/crud/:model/:id/:associacao/:associacao_id' => "crud#show", as: :crud_associacao_model
    end
  end
end

app/helpers/crud_helper.rb
module CrudHelper

  def is_active_controller(controller_name)
    params[:controller] == controller_name ? "active" : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? "active" : nil
  end

  def is_raro_crud(classe)
    #if(Rails.env == "production")
    #  @@cruds = Dir[Rails.root.join("app","raro_crud","*.rb")].map{|f| f.split(/\//).last.gsub(/_crud\.rb/,'')} unless @@cruds
    #else
      @@cruds = Dir[Rails.root.join("app","raro_crud","*.rb")].map{|f| f.split(/\//).last.gsub(/_crud\.rb/,'')}
    #end
    return @@cruds.include?(classe.underscore.to_s)
  end

  def lista_menus_crud(raro_models)
    menus = []
    raro_models.each do |modelo|
      menus << ['crud', "#{modelo.name.underscore}"]
    end
    menus
  end

  def menu_helper_crud(modelo, url, nome, classe, icon='')
    if can?(:read, classe)
      buffer = ""
      buffer << "<li class='childreen #{controller.controller_name == 'crud' and params[:model] == modelo ? 'active' : '' }'>"
      buffer << link_to("<i class='#{icon}'></i><span>#{nome}</span>".html_safe, url, data: {push: true, crumb: 'wielka'})
      buffer << "</li>"
      buffer.html_safe
    end
  end

  def is_action_edit?
    params[:action] == "edit"
  end

  def is_action_create?
    params[:action] == "create"
  end

  def is_action_show?
    params[:action] == "show"
  end

  def is_action_new?
    params[:action] == "new"
  end

  def is_action_index?
    params[:action] == "index"
  end

  def is_action_query?
    params[:action] == "query"
  end


  def render_link(link,url)
    nome_modelo = I18n.t("model.#{link[:modelo].underscore}")
    if link[:partial].present?
      render link[:partial]
    elsif link[:link].present?
      link_to "#{gen_icon(link[:icon])} #{I18n.t(link[:text], model: nome_modelo)}".html_safe, "#{url}/#{link[:link]}", class: link[:class], data: data(link)
    else
      link_to "#{gen_icon(link[:icon])} #{I18n.t(link[:text], model: nome_modelo)}".html_safe, link[:url], class: link[:class], data: data(link)
    end
  end

  def gen_icon(i)
    if i
      "<i class='#{i}'></i>"
    else
      ""
    end
  end

  def data(link)
    data = {}
    link[:data].each_key{|k| data[k] = link[:data][k]} if link[:data]
    return data
  end

  def raro_models
    models = []
    Dir["#{Rails.root.to_s}/app/raro_crud/*"].each do |f|
      m = f.split("/").last.split("_crud").first.camelize
      if m != "Raro"
        models << m.constantize
      end
    end
    models.uniq.flatten
  end

  def raro_permissions
    permissions = []
    Dir["#{Rails.root.to_s}/app/controllers/*"].each do |f|
      permission = f.split("/").last.split(".").first.camelize.constantize.instance_variable_get("@permissao")
      if permission.present?
        permissions << permission
      end
    end
    raro_models.each do |m|
      permissions << m.name
    end
    permissions.uniq.flatten
  end

  def render_plus_button(field,f,modelo,record)
    field[:sf][:wrapper] = :with_button
    render_field(field,f,modelo,record)
  end

  def render_field(field,f,modelo,record)
    field[:sf][:wrapper] ||= :default
    if field[:sf].present? && field[:sf][:if].present?
      return unless field[:sf][:if].call(f.object)
    end
    field[:sf][:hint] = false if field[:sf].present? && !field[:sf][:hint].present?
    if field[:sf].present? && field[:sf][:date_format].present? && f.object.send(field[:attribute]).present? && Date <= modelo.columns_hash[field[:attribute].to_s].type.to_s.camelcase.constantize
      field[:sf][:input_html] ||= {}
      field[:sf][:input_html][:value] = f.object.send(field[:attribute]).strftime(field[:sf][:date_format])
    end
    if !field[:sf][:edit].nil? || !field[:sf][:create].nil?
      if !field[:sf][:edit].nil? && !field[:sf][:edit] && !record.new_record?
      elsif !field[:sf][:create].nil? && !field[:sf][:create] && record.new_record?
      else
        opts = field[:sf].merge(label: I18n.t(field[:sf][:label], default: I18n.t("shared.#{field[:attribute]}")))
        unless modelo.reflect_on_association(field[:attribute])
          if modelo.new.send(field[:attribute]).class.to_s =~ /Uploader/ and f.object.send(field[:attribute]).present?
            f.input field[:attribute], opts.merge(hint: "Arquivo Atual: #{f.object.send(field[:attribute]).file.filename}")
          else
            f.input field[:attribute], opts
          end
        else
           f.association field[:attribute], opts
        end
      end
    else
      if field[:sf][:value] and field[:sf][:value].class == Proc
         field[:sf][:input_html] ||= {}
         field[:sf][:input_html][:value] = f.instance_eval(&field[:sf][:value])
      end
      if field[:sf][:collection_if] and field[:sf][:collection_if].class == Proc
         field[:sf][:collection] = f.instance_eval(&field[:sf][:collection_if])
      end
      opts = field[:sf].merge(label: I18n.t(field[:sf][:label], default: I18n.t("shared.#{field[:attribute]}")))
      unless modelo.reflect_on_association(field[:attribute])
        if modelo.new.send(field[:attribute]).class.to_s =~ /Uploader/ and f.object.send(field[:attribute]).present?
          f.input field[:attribute], opts.merge(hint: "Arquivo Atual: #{f.object.send(field[:attribute]).file.filename}")
        else
          f.input field[:attribute], opts
        end
      else
        f.association field[:attribute], opts
      end
    end
  end

  def imagem?(file)
    file.present? && file.content_type.start_with?('image')
  end

  def video?(file)
    file.present? && file.content_type.start_with?('video')
  end

  def documento?(file)
    !(video?(file) || imagem?(file))
  end

  def render_field_file(field)
		if imagem?(field) && field.respond_to?(:thumb)
      if is_active_action("printing")
        pdf_image_tag(field, width: '100px')
      else
        link_to field.url, target: "_blank" do
          image_tag(field.url(:thumb), width: '100px')
        end
      end
		elsif video?(field)
			link_to field, field.url, target: "_blank"
		else
			link_to field, field.url, target: "_blank"
		end
  end

  def render_crud(&block)
    render "/crud/shared", block: block
  end

  def render_default_actions_crud
    render "default_actions_crud"
  end

  #Permissions
  def should_view?(crud_helper, record)
    return false unless can?(:read, record)
    return true if crud_helper.condition_view_action.nil?
    crud_helper.condition_view_action.call(record)
  end

  def should_edit?(crud_helper, record)
    return false unless can?(:update, record)
    return true if crud_helper.condition_edit_action.nil?
    crud_helper.condition_edit_action.call(record)
  end

  def should_destroy?(crud_helper, record)
    return false unless can?(:destroy, record)
    return true if crud_helper.condition_destroy_action.nil?
    crud_helper.condition_destroy_action.call(record)
  end

  def should_listing?(crud_helper, model)
    return false unless can?(:read, model)
    return true if crud_helper.condition_listing_action.nil?
    crud_helper.condition_listing_action.call(model)
  end

  def should_listing_excel?(crud_helper, model)
    return false unless can?(:read, model)
    return true if crud_helper.condition_listing_excel.nil?
    crud_helper.condition_listing_excel.call(model)
  end

  def can_print_pdf?(crud_helper, record)
    return false unless can?(:read, record)
    return true if crud_helper.condition_printing_action.nil?
    crud_helper.condition_printing_action.call(record)
  end

  private

  def pdf_image_tag(field, options = {})
    if Rails.env.development? || Rails.env.test?
      # Unless running a web server that can process 2 requests at the same
      # time, trying to insert an image in a PDF creates a deadlock: the server
      # can't finish processing the PDF request until it gets the image, but it
      # can't start processing the image request until it has finished
      # processing the PDF request.
      # This will not be a problem in production, but in dev, a workaround is
      # to base64 the image and insert its contents into the HTML
      if field.respond_to?(:thumb)
        image_data = File.read(field.thumb.path)
      else
        image_data = Rails.application.assets[field].to_s
      end
      image_tag("data:image/png;base64,#{::Base64.encode64(image_data)}", options)
    else
      if field.respond_to?(:thumb)
        field = field.thumb.url
      end
      wicked_pdf_image_tag(field, options)
    end
  end

end

app/views/crud/_crud_template.html.erb
<% unless params[:render] == 'modal' %>
	<% content_for :breadcumb do %>
		<% if @crud_associacao.present? %>
			<li class="breadcrumb-item"><%= link_to @crud_associacao.title, crud_models_path(model: @crud_associacao.root_path) %></li>
			<li class="breadcrumb-item"><%= link_to @crud_helper.title, @clean_url %></li>
		<% else %>
			<li class="breadcrumb-item"><%= link_to @crud_helper.title, crud_models_path(model: @crud_helper.root_path) %></li>
		<% end %>
	<% end %>


	<% content_for :header do %>
		<%=@crud_helper.title%>
	<% end %>

	<% content_for :scopes do %>
		<%= render "/crud/scopes" %>
	<% end %>

	<% content_for :modal do %>
		<% if @crud_helper.search_fields.present? %>
			<%= render '/crud/search' %>
		<% end %>
	<% end %>
<% end%>

<%= render 'layouts/template_raro_crud' %>

app/views/crud/_default_actions_crud.html.erb
<%= submit_tag(I18n.t("save"), class: "btn btn-primary") %>
<%= link_to I18n.t("undo"), crud_models_path(model: @model.name.underscore), class: 'btn btn-default', data: { push: 'partial', target: "#form" } %>

app/views/crud/_edit.html.erb
<%= render "/crud/form" %>

app/views/crud/_form.html.erb
<%= render_crud do %>
	<div class="modal inmodal" id="modal_new_record" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content animated bounceInRight">
				<div class="modal-body">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-white" data-dismiss="modal"><%= I18n.t("cancel") %></button>
				</div>
			</div>
		</div>
	</div>
	<%unless params[:render] == 'modal'%>
		<% if @record.new_record? %>
			<% if @crud_associacao.present? %>
				<% url = create_crud_associacao_path(model: params[:model], id: params[:id], associacao: params[:associacao], page: params[:page], q: params[:q].try(:to_unsafe_h)) %>
			<% else %>
				<% url = create_crud_path(model: @model.name.underscore, page: params[:page], q: params[:q].try(:to_unsafe_h)) %>
			<% end %>
		<% else %>
			<% if @crud_associacao.present? %>
				<% url = update_crud_associacao_path(model: params[:model], id: params[:id], associacao: params[:associacao], associacao_id: @record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)) %>
			<% else %>
				<% url = update_crud_path(model: @model.name.underscore, id: @record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)) %>
			<% end %>
		<% end %>
		<% remote_form = false%>
	<%else%>
		<% url = "#{@clean_url}/#{@record.new_record? ? 'create?render=modal' : @record.id.to_s+'/create?render=modal'}" %>
		<% remote_form = true%>
	<%end%>
	<%= simple_nested_form_for @record, remote: remote_form, html: {class: "form-horizontal"}, url: url do |f| %>
		<%= flash_messages_error(@record.errors) %>
		<% @crud_helper.form_fields.each_with_index do |field, index| %>
			<% if field[:sf][:agrupamento].present? && (index == 0 || @crud_helper.form_fields[index - 1][:sf][:agrupamento] != field[:sf][:agrupamento]) %>
				<div class="col-sm-12">
					<h3><%= I18n.t(field[:sf][:agrupamento]) %></h3>
				</div>
			<% end %>
			<% if field[:sf][:if].present? %>
				<% next unless field[:sf][:if].call(f.object) %>
			<% end %>
			<% if field[:sf][:grupo].present? %>
				<%= render "/crud/form_group", f: f, key: field[:attribute], groups: field[:sf] %>
			<% else %>
				<% if @model.reflect_on_association(field[:attribute]).try(:macro) == :belongs_to && is_raro_crud(@model.reflect_on_association(field[:attribute]).class_name) && field[:sf][:add_registro].nil?%>
						<%= render_plus_button(field,f,@model,@record) %>
				<%else%>
						<%= render_field(field,f,@model,@record) %>
				<%end%>
			<% end %>
			<% if field[:sf][:separador].present? %>
				<hr>
			<% end %>
		<% end %>
		<%@crud_helper.form_groups.each do |key, groups|%>
			<%= render "/crud/form_group", f: f, key: key, groups: groups %>
		<% end %>
		<div class="form-group">
			<div class="col-sm-4 col-sm-offset-2">
				<%= f.submit I18n.t("save"), class: 'btn btn-primary'  %>
				<%unless params[:render] == 'modal'%>
					<%= link_to I18n.t("undo"), @url, class: 'btn btn-default', data: {push: 'partial', target: "#form"} %>
				<% end %>
			</div>
		</div>
	<% end %>
	<% @crud_helper.form_scripts.each do |script| %>
		<%= javascript_include_tag "crud/#{script}" %>
	<% end %>
<% end %>

app/views/crud/_form_group.html.erb
<% modelo = f.object.class.reflect_on_association(key.to_s).class_name.constantize %>
<% if f.object.present? && !f.object.send(key).present? %>
	<% if [:has_many,:has_and_belongs_to_many].include?(f.object.class.reflect_on_association(key).macro) %>
		<% f.object.send(key).build %>
	<% else %>
		<% f.object.send("build_#{key}") %>
	<% end %>
<% end %>
<%= f.simple_fields_for key do |g| %>
	<div class="col-sm-12">
		<h4><%= I18n.t(groups[:label]) %></h4>

	</div>
	<hr />
	<% groups[:fields].each do |field| %>
		<% if field[:sf].present? && field[:sf][:grupo].present? %>
			<%= render "/crud/form_group", f: g, key: field[:attribute], groups: field[:sf] %>
		<% else %>
			<% if modelo.reflect_on_association(field[:attribute]).try(:macro) == :belongs_to && is_raro_crud(modelo.reflect_on_association(field[:attribute]).class_name) && field[:sf][:add_registro].nil?%>
					<%= render_plus_button(field,g,modelo,f.object) %>
			<%else%>
					<%= render_field(field,g,modelo,f.object) %>
			<%end%>
		<% end %>
	<% end %>
	<% if [:has_many,:has_and_belongs_to_many].include?(f.object.class.reflect_on_association(key).macro) %>
		<div class="form-group row">
			<div class="col-sm-12">
				<%= g.link_to_remove "#{I18n.t('destroy')} #{I18n.t(groups[:sublabel] || groups[:label])}", class: 'float-right btn btn-danger btn-sm' %>
			</div>
		</div>
	<% end %>
<% end %>
<% if [:has_many,:has_and_belongs_to_many].include?(f.object.class.reflect_on_association(key).macro) %>
	<div class="form-group row">
		<div class="col-sm-12">
			<%= f.link_to_add "#{I18n.t('add')} #{I18n.t(groups[:sublabel] || groups[:label])}", key, class: 'float-right btn btn-primary btn-sm' %>
		</div>
	</div>
<% end %>

app/views/crud/_new.html.erb
<%= render "/crud/form" %>

app/views/crud/_record.html.erb
<%= content_tag :tr, id: "record-#{record.id}" do %>
	<% @crud_helper.index_fields.each do |att| %>
		<% if !att[:visible_if].nil?%>
			<% if ((att[:visible_if].class == Proc && !att[:visible_if].call(record)) || (att[:visible_if].class != Proc && !att[:visible_if])) %>
				<% next %>
			<% end %>
		<% end %>
		<% if record.send(att[:attribute]).present? or record.send(att[:attribute]).to_s == "false"%>
			<% if @model.columns_hash[att[:attribute].to_s].present? && [:date, :time, :datetime].include?(@model.columns_hash[att[:attribute].to_s].type)%>
				<td class="">
					<div class="col-xs-9">
						<% if att[:date_format].present?%>
							<%= I18n.l(record.send(att[:attribute]), format: att[:date_format]) %>
						<% else %>
							<%= I18n.l(record.send(att[:attribute])) %>
						<% end %>
					</div>
				</td>
			<% elsif @model.reflect_on_association(att[:attribute]) && @model.reflect_on_association(att[:attribute]).macro != :belongs_to && @model.reflect_on_association(att[:attribute]).macro != :has_one%>
				<td class="">
					<% record.send(att[:attribute]).each do |rec| %>
						<li>
							<% if att[:link_associacao] %>
								<%= link_to crud_model_path(model: rec.class_name.to_s.underscore, id: rec.id) do %>
									<%= rec.to_s %>
								<% end %>
							<% else %>
								<%= rec.to_s %>
							<% end %>
						</li>
					<% end %>
				</td>
			<% elsif record.send(att[:attribute]).class == Array %>
				<td class="">
					<% record.send(att[:attribute]).each do |rec| %>
						<li>
							<%= rec.to_s %>
						</li>
					<% end %>
				</td>
			<% elsif record.send(att[:attribute]).respond_to?(:url) and record.send(att[:attribute]).url(:thumb) %>
				<td class="">
					<%= link_to record.send(att[:attribute]).url, target: "_blank" do %>
						<%= image_tag(record.send(att[:attribute]).url(:thumb)) %>
					<% end %>
				</td>
			<% else %>
				<% if record.send(att[:attribute]).to_s == "false" or record.send(att[:attribute]).to_s == "true" %>
					<td class="">
						<div class="col-xs-9">
							<%= I18n.t(record.send(att[:attribute]) ? "shared.sim" : "shared.nao") %>
						</div>
					</td>
				<% else %>
					<td class="">
						<div class="col-xs-9">
							<% if att[:label_method].present? && record.send(att[:attribute]).present?%>
								<% if @model.reflect_on_association(att[:attribute]) && att[:link_associacao] %>
									<%= link_to crud_model_path(model: @model.reflect_on_association(att[:attribute]).class_name.to_s.underscore, id: record.send(att[:attribute]).id) do %>
										<%= record.send(att[:attribute]).send(att[:label_method]) %>
									<% end %>
								<% else %>
									<%= record.send(att[:attribute]).send(att[:label_method]) %>
								<% end %>
							<% else %>
								<% if @model.reflect_on_association(att[:attribute]) && att[:link_associacao] %>
									<%= link_to crud_model_path(model: @model.reflect_on_association(att[:attribute]).class_name.to_s.underscore, id: record.send(att[:attribute]).id) do %>
										<%= record.send(att[:attribute]).to_s %>
									<% end %>
								<% else %>
									<%= record.send(att[:attribute]).to_s %>
								<% end %>
							<% end %>
						</div>
					</td>
				<% end %>
			<% end %>
		<% else %>
			<td class=""></td>
		<% end %>
	<%end%>
	<% if @crud_helper.view_action || @crud_helper.edit_action || @crud_helper.destroy_action || @crud_helper.actions.present? || @crud_helper.actions_links.present? %>
		<td class="">
			<div class="col-xs-9">
				<% @crud_helper.actions.each do |action| %>
					<% if (action[:proc].present? && action[:proc].call(record)) || !action[:proc].present? %>
						<% if action[:options].present? && action[:options][:wiselink].present? && action[:options][:wiselink] %>
							<% data = {push: "partial", target: "#form"} %>
            <% end %>
            <% if @crud_associacao.present? %>
              <%= link_to I18n.t(action[:desc]), action_crud_associacao_path(model: params[:model], id: params[:id], associacao: params[:associacao], associacao_id: record.id, acao: action[:method], page: params[:page], q: params[:q].try(:to_unsafe_h)), class: "btn btn-primary btn-sm", data: data || {} %>
            <% else %>
              <%= link_to I18n.t(action[:desc]), action_crud_path(model: @model.name.underscore, id: record.id, acao: action[:method], page: params[:page], q: params[:q].try(:to_unsafe_h)), class: "btn btn-primary btn-sm", data: data || {} %>
            <% end %>
					<% end %>
				<% end %>
				<% @crud_helper.actions_links.each do |name, options| %>
					<% unless (options[:can].present? && !record.instance_eval(&options[:can])) %>
						<% if options[:url].present? %>
							<% url = options[:url] %>
							<% if options[:id] %>
								<% url += options[:url].include?("?") ? "&id=#{record.id}" : "?id=#{record.id}" %>
							<% else url.include?(":id") %>
								<% url = url.gsub(":id", "#{record.id}") %>
							<% end %>
							<% if options[:wiselink].present? && options[:wiselink] %>
								<a href="<%= url %>" class="btn btn-success btn-sm" data-push="partial" data-target="#form">
									<%= I18n.t(name) %>
								</a>
							<% else %>
								<a href="<%= url %>" class="btn btn-success btn-sm">
									<%= I18n.t(name) %>
								</a>
							<% end %>
						<% elsif options[:associacao].present? %>
							<% if options[:wiselink].present? && options[:wiselink] %>
								<%= link_to I18n.t(name), crud_associacao_models_path(model: @model.name.underscore, id: record.id, associacao: options[:associacao].to_s), class: "btn btn-success btn-sm", data: {push: true, crumb: "wielka"} %>
							<% else %>
								<%= link_to I18n.t(name), crud_associacao_models_path(model: @model.name.underscore, id: record.id, associacao: options[:associacao].to_s), class: "btn btn-success btn-sm" %>
							<% end %>
						<% elsif options[:partial].present? %>
							<%= render options[:partial], record: record, action: :index %>
						<% end %>
					<% end %>
				<% end %>
				<% if @crud_helper.view_action && should_view?(@crud_helper, record) %>
					<% link_text = TemplusModels.configuration.usar_icones ? "<i class='fa fa-eye'></i>".html_safe : I18n.t("view") %>
					<% if @crud_associacao.present? %>
						<%= link_to link_text, crud_associacao_model_path(model: params[:model], id: params[:id], associacao: params[:associacao], associacao_id: record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)), class: 'btn btn-primary btn-sm', data: {push: 'partial', target: '#form'} %>
					<% else %>
						<%= link_to link_text, crud_model_path(model: @model.name.underscore, id: record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)), class: 'btn btn-primary btn-sm', data: {push: 'partial', target: '#form'} %>
					<% end %>
				<% end %>
				<% if @crud_helper.edit_action && should_edit?(@crud_helper, record) %>
					<% link_text = TemplusModels.configuration.usar_icones ? "<i class='fa fa-edit'></i>".html_safe : I18n.t("edit") %>
					<% if @crud_associacao.present? %>
						<%= link_to link_text, edit_crud_associacao_path(model: params[:model], id: params[:id], associacao: params[:associacao], associacao_id: record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)), class: 'btn btn-primary btn-sm', data: {push: 'partial', target: '#form'} %>
					<% else %>
						<%= link_to link_text, edit_crud_path(model: @model.name.underscore, id: record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)), class: 'btn btn-primary btn-sm', data: {push: 'partial', target: '#form'} %>
					<% end %>
				<% end %>
				<% if @crud_helper.destroy_action && should_destroy?(@crud_helper, record) %>
					<% link_text = TemplusModels.configuration.usar_icones ? "<i class='fa fa-trash'></i>".html_safe : I18n.t("destroy") %>
					<% if @crud_associacao.present? %>
						<%= link_to link_text, destroy_crud_associacao_path(model: params[:model], id: params[:id], associacao: params[:associacao], associacao_id: record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)), class: 'btn btn-danger btn-sm', data: {method: 'delete', confirm: I18n.t('mensagem_confirm_destroy')} %>
					<% else %>
						<%= link_to link_text, destroy_crud_path(model: @model.name.underscore, id: record.id, page: params[:page], q: params[:q].try(:to_unsafe_h)), class: 'btn btn-danger btn-sm', data: {method: 'delete', confirm: I18n.t('mensagem_confirm_destroy')} %>
					<% end %>
				<% end %>
			</div>
		</td>
	<% end %>
<% end %>

app/views/crud/_scopes.html.erb
<% if @crud_helper.scopes.present? %>
	<% if @crud_helper.scopes.class == Array %>
		<% @crud_helper.scopes.each do |escopo| %>
			<%= link_to crud_models_path(model: @model.name.underscore, scope: escopo[0]), id: "#{escopo[0]}", data: {push: true, crumb: 'wielka'} do%>
				<div style="float: left; margin-left: 10px;">
					<div class="widget style1 gray-bg" style="padding: 15px 10px !important;">
						<div class="row vertical-align text-center" style="margin:0!important;">
							<h3 class="font-bold" style="width:100%;">
								<%= I18n.t(escopo[1]) %>
								<span class="label label-success pull-right" style="margin-left: 10px;">
									<% if current_usuario.present? %>
										<%= @model.send(escopo[0]).accessible_by(current_ability, :read).count %>
									<% else %>
										<%= @model.send(escopo[0]).count %>
									<% end %>
								</span>
							</h3>
						</div>
					</div>
				</div>
			<%end%>
		<% end %>
	<% else %>
		<%= render @crud_helper.scopes %>
	<% end %>
<% end %>

app/views/crud/action.html.erb
<% content_for :corpo do %>
	<div id="form" >
		<%= render "/#{@model.name.underscore.pluralize}/#{params[:acao]}" %>
	</div>
<% end %>

<%= render "/crud/crud_template" %>